# Generated by Django 2.2.7 on 2019-11-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=1000)),
                ('instagram', models.CharField(max_length=1000)),
                ('logo', models.CharField(max_length=1024)),
            ],
        ),
    ]
