version: '3.3'
services:
  cleanspace-backend:
    image: cleanspace-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.cleanspace-backend-https.redirectscheme.scheme=https"
      - "traefik.http.routers.cleanspace-backend-http.entrypoints=web"
      - "traefik.http.routers.cleanspace-backend-http.rule=Host(`api.r4.ie`)"
      - "traefik.http.routers.cleanspace-backend-http.middlewares=cleanspace-backend-https@docker"
      - "traefik.http.routers.cleanspace-backend.entrypoints=web-secure"
      - "traefik.http.routers.cleanspace-backend.rule=Host(`api.r4.ie`)"
      - "traefik.http.routers.cleanspace-backend.tls=true"
      - "traefik.http.routers.cleanspace-backend.tls.certresolver=default"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
  traefik:
    internal: true
